<?php

class Book{
    // Khai báo các thuộc tính (property)
    private $id;
    private $title;
    private $author;
    private $publicationYear;
    private $imageReview;
    private $type;

    // Phương thức (method) khởi tạo
    public function __construct($title, $author, $publicationYear) {
        $this->title = $title;
        $this->author = $author;
        $this->publicationYear = $publicationYear;
    }
    // Getter setter
    public function setTitle($title){
        $this->title = $title;
    }
    public function setAuthor($author){
        $this->author = $author;
    }
    public function setPublicationYear($publicationYear){
        $this->publicationYear = $publicationYear;
    }

    public function getTitle(){
        return $this->title ;
    }
    public function getAuthor(){
        return $this->author;
    }
    public function getPublicationYear(){
        return $this->publicationYear ;
    }

    public function showInfo() {
        echo "Tiêu đề: {$this->title}\n";
        echo "Tác giả: {$this->author}\n";
        echo "Năm xuất bản: {$this->publicationYear}\n";
    }

}

class PaperBook extends Book {
    private $weight;
    public function __construct($title, $author, $publicationYear, $weight) {
        parent::__construct($title, $author, $publicationYear); // Gọi đến hàm khởi tạo của lớp cha
        $this->weight = $weight;
    }

    public function setWeight($weight) {
        $this->weight = $weight;
    }

    public function getWeight() {
        return $this->weight;
    }

    public function showInfo()
    {
        parent::showInfo(); // TODO: Change the autogenerated stub
        echo "Khối lượng: {$this->weight}\n";
    }

}

class EBook extends Book {
    private $size;
    public function __construct($title, $author, $publicationYear, $size) {
        parent::__construct($title, $author, $publicationYear); // Gọi đến hàm khởi tạo của lớp cha
        $this->size = $size;
    }

    public function setSize($size) {
        $this->size = $size;
    }

    public function getSize() {
        return $this->size;
    }

    public function showInfo()
    {
        parent::showInfo();
        echo "Dung lượng: {$this->size}\n";
    }

}

$paperBook = new PaperBook("Conan", "Tác giả A", 2022, 1.5);
$paperBook->showInfo();

$eBook = new EBook("Doraemom", "Tác giả B", 2022, 10);
$eBook->showInfo();